# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Infinite Thoughts
tagline:          'My personal blog currently built on Hyde'
description:      '博客正在建设中，许多前端还在开发当中。'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ethan'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/poole/hyde
